### ISSUE TITLE
Ship 2.0

### ISSUE THREAD

**Issue by mixonic** [mixonic/ember-cli-deprecation-workflow#109]
This issue tracks work blocking the release of a final 2.0 release.

ember-cli-deprecation-workflow 2.0 will introduce the following breaking changes:

* Ember 2.12-LTS is the minimum version of Ember supported. Support for older versions of Ember (for example back to 1.13.0) is removed.
* Ember CLI 3.16+ is the minimum version of Ember CLI supported.
* Many dependency changes land in 2.0
* Node 12.x and >= 14.x are the minimum versions of Node supported. Support for Node 6.x, 8.x, 10.x, 11.x, and 13.x is removed.

TODO:

See also https://github.com/mixonic/ember-cli-deprecation-workflow/labels/2.0

* [x] https://github.com/mixonic/ember-cli-deprecation-workflow/pull/93 or some similar support for limiting deprecation logging
* [x] Re-assert that 3.16 is the minimum version. @mixonic would like to support back to 2.12. https://github.com/mixonic/ember-cli-deprecation-workflow/pull/110
* [x] Resolve known issues with test helpers after landing https://github.com/mixonic/ember-cli-deprecation-workflow/pull/110. Support for Node 16 during test is broken.
* [x] https://github.com/mixonic/ember-cli-deprecation-workflow/pull/107 or a similar fix to avoid touching the Ember global when possible. This also means followup on https://github.com/mixonic/ember-cli-deprecation-workflow/pull/110 to address the test helpers likely touching the Ember global.
* [x] Green suite for 3.27+ https://github.com/mixonic/ember-cli-deprecation-workflow/pull/111

**Comment by chancancode** [comment]
Probably a good opportunity to drop Node 10 as well?

**Comment by mixonic** [comment]
I would like to support old versions of Ember, as the point of this library is to help complex/large apps upgrade and there are many not on 3.16.

However I have no problem requiring Ember CLI 3.16+ and something newer than Node 10. The addon isn't helping upgrade those things, apps can upgrade them independently of Ember and should.

**Comment by chancancode** [comment]
Yeah I think that’s consistent with the support policies. Since node 10 is EOL, if we don’t drop it now we are going to have issues when other deps start dropping node 10, especially when not all of them bump major when doing so.

**Comment by rwjblue** [comment]
Ya, let’s make node engines `12.* || >= 14` (dropping 10 and 13, both of which are EOL).

**Comment by gilest** [comment]
This can be closed, yes?

**Comment by mixonic** [comment]
🎉  Yep!
