### ISSUE TITLE
[possible bug]: `TypeError: require.has is not a function`

### ISSUE THREAD

**Issue by foxtree** [mixonic/ember-cli-deprecation-workflow#128]
Hi, I am attempting to upgrade an ember app from `3.20` to `3.24`, and trying to use this addon to suppress deprecation logging that causes the `ember test` process to hang.

However, after installing and configuring this addon, running `ember test` fails with several errors, including:
![image](https://user-images.githubusercontent.com/3383704/126374941-ea1fc792-255d-4366-85dc-17386207e17b.png)

This appears to be due to the [following line](https://github.com/mixonic/ember-cli-deprecation-workflow/blob/master/vendor/ember-cli-deprecation-workflow/main.js#L33) in 
`vendor/ember-cli-deprecation-workflow/main.js` 

^these errors do not occur when I install and configure `ember-cli-deprecation-workflow@v2.0.0-beta.4`

...Is this a bug with version `2.0`?

**Comment by kategengler** [comment]
I'm seeing this just now after adding `ember-cli-deprecation-workflow@2.0.0` to an existing app already on  Ember v3.24. Seen when running `ember s` and going to the main page of the app.

**Comment by kategengler** [comment]
`ember-classic-decorator` seems to be the problem https://github.com/emberjs/ember-classic-decorator/issues/74

**Comment by foxtree** [comment]
Thanks for replying.

I was able to get `ember-cli-deprecation-workflow@^1.0.1` to work with this particular project, so we'll be holding of on version 2, for now.

**Comment by elwayman02** [comment]
I'm also seeing this error in an open-source project. Here's a failing PR that reproduces it just by bumping this package to 2.0.0:

https://github.com/elwayman02/ember-scroll-modifiers/pull/407/files

**Comment by elwayman02** [comment]
Fix is here, potentially: https://github.com/emberjs/ember-classic-decorator/releases/tag/v2.0.1

**Comment by snewcomer** [comment]
This can be closed.  Verified!
