### ISSUE TITLE
Ember install fails for addon

### ISSUE THREAD

**Issue by ksnyde** [mixonic/ember-cli-deprecation-workflow#21]
After typing `ember install ember-cli-deprecation-workflow` I get:

> Cannot read property 'name' of undefined

I remember this error used to come up a lot in addons a few months back but hoping you know what to do next to get this working. It is possible this error is still a common snag for addons and maybe I've just reflexively fallen back to using `npm install ...` in many cases and then digging around for the bower modules that _ember install_ would have installed (this package doesn't seem to rely on any Bower though). 

In either case, the current state of affairs is that typing `deprecationWorkflow.flushDeprecations()` from the browser's console results in:

> Uncaught ReferenceError: deprecationWorkflow is not defined

**Comment by rwjblue** [comment]
Yeah, `npm install --save-dev ember-cli-deprecation-workflow` should definitely work (let me know if it doesn't).  

I'll look into that error with `ember install ember-cli-deprecation-workflow` to see what needs to be fixed.

**Comment by ksnyde** [comment]
It didn't work for me. I hope I'm not doing anything silly but it definitely didn't work. On the chance you wanted to look at the actual code it is OSS:

GitHub: [https://github.com/lifegadget/ui-button](https://github.com/lifegadget/ui-button)
Divshot: [dummy app](http://development.ui-button.divshot.io/), [tests](http://development.ui-button.divshot.io/tests)

**Comment by ksnyde** [comment]
BTW, not your problem unless you're interested ... I'd love your eyeballs but digging around in other people's code might not be best use of your time. Well ... you decide.

Side note, I'm still using Ember-CLI 1.13.1 ... will probably bump 1.13.6 soon. Just wondering if I should at least bump up my **ember-cli-qunit** as I see its gone through some revs (I'm on `0.3.15`)

**Comment by efx** [comment]
`npm install --save-dev ember-cli-deprecation-workflow` worked flawlessly for me in an ember-cli@2.3.0 project.

**Comment by rwjblue** [comment]
Sorry for the delays here, I think this is working well at this point, closing...
