### ISSUE TITLE
Ember-data not loading when changing `silence` to `throw`

### ISSUE THREAD

**Issue by ultimatemonty** [mixonic/ember-cli-deprecation-workflow#23]
When everything is set to `silent` the app loads fine. As soon as I set any deprecations to `throw` the app won't load and I get `this.store.findRecord is not a function` in the console. Change the `throw` back to `silent` and everything works again.

Library | Version
--------- | -----------
Ember Inspector | **1.9.0**
Ember | **1.13.6**
jQuery | **1.11.3**
Ember-Data | **1.13.7**
Ember-CLI | **1.13.7**

```javascript
// config/deprecation-workflow.js
window.deprecationWorkflow = window.deprecationWorkflow || {};
window.deprecationWorkflow.config = {
  workflow: [
    { handler: "silence", matchMessage: "Using `Ember.HTMLBars.makeBoundHelper` is deprecated. Please refactor to using `Ember.Helper` or `Ember.Helper.helper`." },
    { handler: "silence", matchMessage: "Using Ember.HTMLBars._registerHelper is deprecated. Helpers (even dashless ones) are automatically resolved." },
    { handler: "silence", matchMessage: "The ActiveModelSerializer has been moved into a plugin. It will not be bundled with Ember Data in 2.0" }
  ]
};

```

**Comment by rwjblue** [comment]
This is pretty much expected.  If you change to `throw` that means that an error is thrown instead of allowing the deprecated behavior to run (and help keep things from crashing).

**Comment by ultimatemonty** [comment]
@rwjblue ahhhhhh that makes sense. My initial understanding was that it would only throw that single deprecation. Thanks for the clarification!

**Comment by rwjblue** [comment]
`log` would be to do the "normal" behavior and log to the console.  Using `throw` means KA-BOOM! :smiley_cat:
