### ISSUE TITLE
Add support for `idMatch`.

### ISSUE THREAD

**Issue by rwjblue** [mixonic/ember-cli-deprecation-workflow#3]
All calls to `Ember.deprecate` will include an `id` and `until` in Ember 2.0.0.  This addon can take advantage of that, to allow much better matching support (id's don't get dynamic interpolation).

**Comment by gjastrab** [comment]
Heard this mentioned on Ember.Land so thought I'd give it a whirl. This is my first contribution to anything Ember related so be gentle :smiley:  (I'm primarily a Rails dev so still figuring things out in the node/npm ecosystem), but let me know if this is what you had in mind and if I'm on the right track. Thanks!

**Comment by koryteg** [comment]
I think you should do a minor or patch version bump for this, because 0.1.4 doesn't pick it up yet.

**Comment by rwjblue** [comment]
Done!
