### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined at deprecationCollector

### ISSUE THREAD

**Issue by tribou** [mixonic/ember-cli-deprecation-workflow#36]
I think [this change](https://github.com/mixonic/ember-cli-deprecation-workflow/commit/36b7e599d35c428cb4465b505cafb74abcebba9d) (0.2.0 to 0.2.1) may have broken my build...

```
TypeError: Cannot read property 'id' of undefined at deprecationCollector
```

I have an existing `config/deprecation-workflow.js` for an Ember v1.13.12 and Ember Data v1.13.16 project which was populated with a substantial `matchMessage` array.  I believe it was parsing a `Ember.SortableMixin is deprecated and was used in...` message and attempted a `var create = Object.create || Ember.create;` just before the exception.

Reverting to v0.2.0 appears to silence the error.

```
ember version
version: 1.13.15
node: 4.4.2
npm: 3.8.5
os: darwin x64
```

**Comment by rwjblue** [comment]
@tribou - What Ember version are you using?

**Comment by kayakyakr** [comment]
Getting this error as well. 

Happens at `vendor/ember-cli-deprecation-workflow/main.js` when options somehow through undefined. Ember is passing `options._suppressDeprecation` for some deprecations, which can be undefined. 

Submitted a real quick PR (#37) to fix
