### ISSUE TITLE
matchId less helpful than matchMessage

### ISSUE THREAD

**Issue by jeffreybiles** [mixonic/ember-cli-deprecation-workflow#38]
Hey!  Love the addon- very useful- but I wanted to push back on a recent change.

The newer versions of ember-cli-deprecation-workflow spit out `matchId` instead of `matchMessage`.  While I agree that this results in fewer repeated messages, it also makes it harder to determine what's going on.

My previous workflow was to google the message, and use context clues from within the message to determine where the problem was originating from.  The new matchId format is difficult to google and removes context clues from the output.  To find the deprecation, I now have to determine which codebase it originated from, search the source code for the matchId, and then hope that not too many context clues are removed.  ([Here's an example](https://github.com/emberjs/data/blob/3e32efe8d6c0a062df9fd8314229a2575ee596a7/addon/-private/system/container-proxy.js#L34) of where important clues are removed- we can no longer tell which lookup is deprecated)

It's possible that there's a new workflow that I don't understand very well that makes matchId a great choice.  If so, could [the matchers section of the README](https://github.com/mixonic/ember-cli-deprecation-workflow#matchers) be updated?

Thanks for all your hard work.

**Comment by rwjblue** [comment]
I agree that the message id's are a bit harder to understand and track down (since the object id's and whatnot are not included in the output).  We did make some recent changes to the deprecation guide to make it easier to find a given deprecation `id`. If you take a look at http://emberjs.com/deprecations/v2.x/ you should be able to find the `id` of any deprecation message listed (from 2.x).

**Comment by jeffreybiles** [comment]
Awesome, that will be very helpful once we get to 2.0.

Do you know if there are plans to add deprecation ids to the Ember 1.x
deprecation guides?

**Comment by rwjblue** [comment]
@jeffreybiles - There are no `id`'s because there were none in the original Ember source code.  I am curious though, if you are not on 2.x you shouldn't be getting `matchId` entries when flushing deprecations (it only happens on 2.0+ when the id's are available).

**Comment by jeffreybiles** [comment]
Interesting!  We're using Ember 1.13.13 and Ember Data 1.13.16, with the
`isNewSerializerAPI` set to true.  Is it possible that we're getting
deprecations that started in a 2.x and were backported to 1.13.x?

**Comment by rwjblue** [comment]
Could be that or Ember Data deprecations (I am not 100% sure when they started introducing deprecation `id`'s).  I guess I'd need to know which ones they are to be certain...

**Comment by jeffreybiles** [comment]
Now that you mention it, it does seem that a good portion of the deprecations originated in Ember Data or other addons (like ember-test-helpers), and there was one (definitely from Ember) that still gave a matchMessage.  That would seem to solve that mini-mystery.

**Comment by rwjblue** [comment]
I'm going to go ahead and close this, since all of the `id`'s are listed in the deprecation guides now.
