### ISSUE TITLE
[Question]: How to prevent stderr maxBuffer exceeded?

### ISSUE THREAD

**Issue by toranb** [mixonic/ember-cli-deprecation-workflow#39]
I've got all my deprecations "silenced" in my app and the browser seems to reflect this when running tests/ember serve. One issue I've found running ember test locally/on jenkins is that I get the fun `stderr maxBuffer exceeded` explosion and I noticed that all these deprecations still seem to be dumping to my console. Is this the intended behavior or is it possible :) I'm doing something wrong that isn't (correctly) silencing this in the console?

Thanks for maintaining a great open source project!

I'm using ember 1.13.13 and ember-cli 2.4.2

**Comment by rwjblue** [comment]
I do not understand exactly what you mean.  When you do `ember build` do you see things in the console?

**Comment by toranb** [comment]
@rwjblue correct - the terminal seems to show these silenced warnings (from any addon the app consumes) in the console. Mostly asking if this is normal / or if this is the normal behavior

**Comment by rwjblue** [comment]
What versions of Ember and ember-cli-deprecation-workflow?

**Comment by rwjblue** [comment]
Build time deprecations happen for template compilation, but recent versions of this lib also silence those too. It is possible though that specific Ember versions need to be patched "specially" to properly silence these build time template compile deprecations.

**Comment by toranb** [comment]
@rwjblue ember 1.13.13 and ember-cli-deprecation-workflow 0.2.2

it's possible this might be ember 1.13 related then? I'll investigate further tomorrow morning (to see if this is template errors/or other). Thanks for the help today Robert !!!

**Comment by toranb** [comment]
@rwjblue I'm getting really close now :) first issue I had was around this fun comment

```js
    if (!htmlbarsCompilerPreprocessor._addon) {
      // not a new enough ember-cli-htmlbars to monkey patch
      // we need 1.0.3
      return;
    }
```

I was using v1.0.1 and bumped to v1.0.5

Next up I console logged the output of "ember" from these lines

```js
      var options = originalHtmlbarsOptions.apply(this, arguments);
      var Ember = options.templateCompiler._Ember;

      console.log('ZZZ');
      console.log(Ember.Debug);
      console.log(Ember.Debug.registerDeprecationHandler);

      if (Ember.Debug && Ember.Debug.registerDeprecationHandler) {
      }
```

It seems the issue (if I'm reading this right) is that `Ember.Debug.registerDeprecationHandler` is undefined. What can I patch/or am I missing another dependency ?

![screen shot 2016-04-27 at 1 33 33 pm](https://cloud.githubusercontent.com/assets/147411/14863841/01a671ac-0c7d-11e6-9d2f-57a4191a7d9d.png)

**Comment by mixonic** [comment]
`registerDeprecationHandler` is 2.1.0+. There is [a polyfill](https://github.com/rwjblue/ember-debug-handlers-polyfill). This library depends on it.

Perhaps the polyfill is nor present during template compilation? That seems pretty plausible.

**Comment by toranb** [comment]
@mixonic that must be - I added the polyfill as you have it in this addon but I still get `undefined` at the moment :(

Anything I can do to get this behavior w/out adding a PR to this addon ... or is that the correct approach now that we've seen an app in the wild break down (dump to console when I expected it would not) ?

**Comment by rwjblue** [comment]
What ember-cli version?

**Comment by toranb** [comment]
@rwjblue 

ember-cli 2.4.2
ember 1.13.13
ember-cli-deprecation-workflow 0.2.2 
ember-debug-handlers-polyfill 1.0.2

**Comment by rwjblue** [comment]
Having `Ember.Debug.registerDeprecationHandler` be undefined should be fine, since we have a fall back for clobbering `Ember.deprecate` itself (which was used by Ember 1.13) here: https://github.com/mixonic/ember-cli-deprecation-workflow/blob/master/index.js#L83

**Comment by toranb** [comment]
Reporting back - looks like logTemplateLintToConsole won't fix the issue :( still dumping template deps to the console

**Comment by rwjblue** [comment]
@toranb - Can you make a repro project (I assume just `ember new foo && cd foo && bower install --save ember#1.13.13` but I want to make sure)?

**Comment by toranb** [comment]
@rwjblue will do - reporting back in just a few

**Comment by toranb** [comment]
@rwjblue simple project does the job as you suggest - now to see if this is because I'm pulling in an addon that has dep warnings in the exported templates

**Comment by toranb** [comment]
@rwjblue annnnd that works also so I'll continue the debug process to see why my actual app is such a broken setup. Sorry for the wasted time here guys - I'll keep at it

**Comment by toranb** [comment]
Super troll - for anyone who might follow this issue (doing all the steps above/still having deps thrown to the console) - look for something "fun" like this in the tests/index.html file of your app

![screen shot 2016-04-27 at 3 37 31 pm](https://cloud.githubusercontent.com/assets/147411/14867425/15a7f7e6-0c8e-11e6-8356-a9dec370246a.png)

**Comment by rwjblue** [comment]
Yeah, that would do it.

**Comment by mixonic** [comment]
😭
