### ISSUE TITLE
Handle template compilation deprecations.

### ISSUE THREAD

**Issue by rwjblue** [mixonic/ember-cli-deprecation-workflow#4]
The current setup only catches deprecations that are fired in the browser. This excludes any compile time deprecations (mostly used by the template compiler). To fix this we need to a way to hook into the node-land template compiler (I do not think that ember-cli-htmlbars exposes everything needed to do this at the moment).

**Comment by mixonic** [comment]
It done! https://github.com/mixonic/ember-cli-deprecation-workflow/pull/33
