### ISSUE TITLE
sinon.getConfig deprecation warning

### ISSUE THREAD

**Issue by hbrysiewicz** [mixonic/ember-cli-deprecation-workflow#44]
Throwing a deprecation warning after updating:

`sinon.getConfig is deprecated and will be removed from the public API in a future version of sinon.`

**Comment by rwjblue** [comment]
This project can only capture and handle `Ember.deprecate` style deprecations. Looks like `sinon` is using something like `console.log` / `console.warn` directly here.

Closing...
