### ISSUE TITLE
Project build is broken and out of date

### ISSUE THREAD

**Issue by eventualbuddha** [mixonic/ember-cli-deprecation-workflow#49]
The last successful `master` build was [build 93](https://travis-ci.org/mixonic/ember-cli-deprecation-workflow/builds/138379147) on 6/17/2016. The build uses node v0.12, which was eclipsed by several LTS releases since then. It's using an old version of just about everything.

Should this project be explicitly archived? Or should it be revived? If revived, is there any way for me to help?

**Comment by dwickern** [comment]
There's some work in progress in #47

**Comment by mixonic** [comment]
@Gaurav0 I left some small notes on https://github.com/mixonic/ember-cli-deprecation-workflow/pull/47. I think updating that PR to bump us all the way to 2.18 would be a great first step.

@eventualbuddha afaik this tool still works despite the failing test suite. I had a colleague use it to get an app from 1.13 -> 2.18 in December and January. I'm not sure where to direct you explicitly in your offer for help: I can say it would be helpful to know this tool still works for 1.13 -> 2.0 and for 2.18 -> 3.0. Even a non-code contribution like documenting the flow further or writing a blog post would be a good way to help people be successful with this tool.

**Comment by rwjblue** [comment]
CI is passing, deps have been updated, etc. Thanks for reporting, and sorry for the delays here...
