### ISSUE TITLE
Warning: Plugin uses .read/.rebuild API

### ISSUE THREAD

**Issue by Vazgen7788** [mixonic/ember-cli-deprecation-workflow#52]
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: TemplateLinter
[API] Warning: Plugin uses .read/.rebuild API: TemplateLinter
[API] Warning: Plugin uses .read/.rebuild API: TemplateLinter

```
ember-cli: 3.1.4
node: 8.9.1
os: linux x64
```

**Comment by rwjblue** [comment]
Thank you for reporting! The issue is that this plugin needs to be rewritten to extend from broccoli-plugin as a base class:

https://github.com/mixonic/ember-cli-deprecation-workflow/blob/master/generate-deprecations-tree.js

**Comment by mixonic** [comment]
@rwjblue would that limit the ability to use this package going back to ember-cli 1.13?

**Comment by rwjblue** [comment]
No, it should be compatible.
