### ISSUE TITLE
Ember.Logger is deprecated

### ISSUE THREAD

**Issue by wagenet** [mixonic/ember-cli-deprecation-workflow#53]
https://github.com/mixonic/ember-cli-deprecation-workflow/blob/2673922d5dbaf6eefd293f93c34bfcadef2303d8/vendor/ember-cli-deprecation-workflow/main.js#L44

**Comment by jrr** [comment]
Amusingly, if you `handler: "log"` the deprecation about using Ember.Logger, it causes infinite recursion and blows the stack.

**Comment by wagenet** [comment]
See #54

**Comment by rwjblue** [comment]
Fixed by https://github.com/mixonic/ember-cli-deprecation-workflow/pull/54
