### ISSUE TITLE
hinting: false

### ISSUE THREAD

**Issue by amk221** [mixonic/ember-cli-deprecation-workflow#63]
If I set hinting to false in `ember-cli-build.js` in development environment (as recommended in this post: https://dockyard.com/blog/2019/06/10/improving-your-dx-on-ember-part-i-quick-wins) then I see deprecation warnings in the console, despite having silenced them via deprecation-workflow.js.

**Comment by rwjblue** [comment]
Hmm, I think I'd remove `ember-cli-eslint` and `ember-cli-template-lint` in favor of `eslint` and `ember-template-lint` directly. That would be a better path than setting `hinting: false`, and is the planned future (we already merged an RFC to move from `ember-cli-eslint` to `eslint`, but the work isn't finished just yet).

**Comment by amk221** [comment]
That's ok, that's what I have done already. I guess I can ignore that `hinting` option then.
Cheers
