### ISSUE TITLE
1.0.1 does not seem to be working

### ISSUE THREAD

**Issue by cah-briangantzler** [mixonic/ember-cli-deprecation-workflow#74]
I have used this addon in the past and it worked as expected. I have an addon that is throwing some deprecations so I tried adding it to this addon. It did not work at all.

I noticed that the flush created a file that had self.deprecationWorkflow, I looked in my other projects and it was window.deprecationWorkflow. I changed it, still didnt not work. I then noticed that the working project was using 0.2.3.   I downgraded the current project from 1.0.1 to 0.2.5 and it started working as expected.

Given that 1.0.1 was released soooo long ago, I cant imagine why other people are not experiencing the same problem when adding it to newer projects.

I am on ember 3.14 as well.

**Comment by ianpetzer** [comment]
Have you maybe switched off tests for your development build in ember-cli.build because I've run into the same problem. Enabling tests for development seems to fix the issue though.

Although, 0.2.5 also doesn't work for me with tests disabled so maybe its a different issue

**Comment by mixonic** [comment]
@cah-briangantzler I'm inclined to fix this as part of the 2.0 release (betas of which are currently `master`) if the problem still exists in 3.14. In general this addon was written for an era way before Ember 3.x, and the 2.0 release will better support that era and is better tested against releases in the 2.x - 4.x (eventually) era.

Closing for now but feel free to re-open if I'm missing something critical, or there is a more narrow analysis of how we could resolve this in the 1.x releases.

**Comment by cah-briangantzler** [comment]
This was so long ago I dont even remember it. I am using deprecation workflow currently and not aware of any problems, so ya, closing is fine. Thanks
